#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=4gb
#PBS -l walltime=00:10:00
#PBS -N deface

#module load freesurfer
#time mri_deface `jq -r '.t1' config.json` \
#	$FREESURFER_HOME/average/talairach_mixed_with_skull.gca \
#	$FREESURFER_HOME/average/face.gca \
#	t1.nii.gz

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;

time singularity exec --writable -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && mri_deface `jq -r '.t1' config.json` $FREESURFER_HOME/average/talairach_mixed_with_skull.gca $FREESURFER_HOME/average/face.gca t1.nii.gz"
