#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=4gb
#PBS -l walltime=00:01:00
#PBS -N deface

module load freesurfer
time mri_deface `jq -r '.t1' config.json` \
	$FREESURFER_HOME/average/talairach_mixed_with_skull.gca \
	$FREESURFER_HOME/average/face.gca \
	t1.nii.gz
